### ISSUE TITLE
1.18.2 Possible to use Flap Wings when Elytra is removed from slot

### ISSUE THREAD

**Issue by Raidobw2** [rejahtavi/betterflight#1]
Hi! When equipping elytras in the 1.18.2 version (`betterflight-1.18-0.6.0.jar`) and unequipping, it's still possible to flap wings a few times before needing to touch ground. It persists after death as well and allow flapping wings with absolutely nothing in the inventory. These are the elytra I tried in various slots, which all work with the flap mechanic:
![image](https://user-images.githubusercontent.com/17010632/163884912-333f5f9e-9e8e-4925-a1e2-7127ecd0a6f3.png)
![image](https://user-images.githubusercontent.com/17010632/163884935-5c80c772-9a60-42cd-89c7-7e45e8ac1fd8.png)
![image](https://user-images.githubusercontent.com/17010632/163884961-1a8ecd00-1f48-49c1-9fa1-0c00b6de5b0e.png)
When you remove one of those elytras, just spam Spacebar and you'll launch upwards and fall down like a rock!

**Comment by Raidobw2** [comment]
Oh also! The elytra widget is not shown for the Customizable Elytra https://www.curseforge.com/minecraft/mc-mods/customizable-elytra when it's equipped in the Back slot or Chestplate slot

**Comment by rejahtavi** [comment]
Hmmm... i definitely have some ideas on how to fix both of these. Pretty sure i just need to refactor the equip checks in general, maybe add a hard depend on caelus.

I should have a chance to dig into the code later this week. Thanks for the report!

**Comment by rejahtavi** [comment]
Turns out it was a simple logic error, easy fix :3

I also added customizable elytra to the default compatibility config.

When you install the new version, delete your config file and the regenerated one will contain compatibility data for customizable elytra.

Alternatively, simply add a "customizableelytra:customizable_elytra" entry to the "elytraItems" list in betterflight-server.toml.

Files are uploaded and pending approval on curseforge and modrinth, they should be there soon. Please test and let me know if everything's fixed. Thanks!

**Comment by Raidobw2** [comment]
Yes it's all fixed! Thank you very much and have a good weekend🙂
