### ISSUE TITLE
Feature : Compatibility with the mod Aileron

### ISSUE THREAD

**Issue by Blugori** [rejahtavi/betterflight#4]
The mod aileron give possibility to the campfires to boost a player flying above it.
I'm suggesting a compatibility upgrade, could you make it so flying above a campfire would recharge the elytra meter to full ?
Thanks for reading !

**Comment by rejahtavi** [comment]
As cool as this idea sounds, I think it would do more harm than good.

The Elytra meter minigame is meant to keep things balanced in betterflight, and to prevent spamming the flap button too much. In early testing, allowing too many flaps would let the player get too high & too fast, and the game would start to glitch with chunk loading errors and the like. It became too easy to fly directly into the ground or a mountain before it visibly loaded in on lower end machines. The meter turned out to be a fun way of preventing that and making the player think about their strategy a bit while flying. Spamming campfires everywhere to keep the meter full would let players "optimize the fun out of the mod" and introduce the potential for frustrating problems.

That said I think you could easily get range extension out of Aileron even without integration, though it will take some finesse. Try to gain altitude off of the campfires and use that as an opportunity to 'rest' and glide for long distances without using the flap button until absolutely necessary. That should let you charge up the meter indirectly using the fires. Feel free to tweak the recharge rate in the configs if needed.

**Comment by Blugori** [comment]
I understand your point of view, I didnt thought about this. The reason I had this reflection is because I wanted to use better flight + aileron, but better flight became too much more efficient than aileron, at a point that aileron would be useless (but I love the 2 mods xD). I read the config files, and tweaking the recharge rate is something I did. To get to the point (XD), I thought those mods would fit together nice, and after reading your answer (thx for answering btw), I still think it could work, but with tweaking configs so it's not broken. To avoid people making campfires everywhere maybe the compatibility could be an option in the config (and so only modpack devs and dedicated players would tweak it) ? But I'm no mod dev and I don't want to put any pressure, so I understand it would be many things to do for just one player xD
Thanks anyway for the mod !  It's awesome

EDIT : After thinking about it, I'm realising I'm not really asking for compatibility but more for a new feature for the recharge system other than the one you created with the hunger bar, and that's maybe not what you planned XD
