### ISSUE TITLE
[Feature Request | 1.18.2] Configurable Speed Boost

### ISSUE THREAD

**Issue by mysticalfoxie** [rejahtavi/betterflight#5]
Hey there!

I love the way you removed the fireworks, because this is exactly what I was looking for. 
The only thing I don't like is that it's so powerful. 

It would feel way better if the flapping should be more often. 
To provide everyone a good choice how strong it should be, you might use a config file. 

Thanks for reading and the great mod! 

Michelle

**Comment by mysticalfoxie** [comment]
Regarding to #2 there exists a config file. 
But at least on client side there's no config file available.
![image](https://user-images.githubusercontent.com/80773420/191996999-d4309088-3ed9-4ca4-b9c7-8bf489228c36.png)

**Comment by rejahtavi** [comment]
There is a client config already. It should be at:
<...>/.minecraft/config/betterflight-client.toml 

However, it only stores volume options and the location of the HUD widget.

All flight parameters are stored in the server-side config, which is inside the world folder at:
<...>/.minecraft/saves/<world-name>/serverconfig/betterflight-server.toml

The server-side configuration is automatically synchronized to the client upon loading the world or joining a server. This is so that all players in any given world have the exact same flight characteristics to keep it fair.

Feel free to play with the values in the file, but keep in mind that I spent a long time balancing the mod to try to make it as fun and useful as possible without being too overpowered or buggy. Making flaps too frequent might cause you to run into performance issues -- that is, you can get going too fast for the world loading to keep up and run straight into things you can't see.
